name: Build docker image and push to DockerHub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t cschembri-docker-mashup .

      - name: Tag Docker image
        run: docker tag cschembri-docker-mashup cschembri/cschembri-docker-mashup

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push cschembri/cschembri-docker-mashup
          